/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.amplitude;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;

import org.appcelerator.titanium.TiApplication;

import org.json.JSONException;
import org.json.JSONObject;

import com.amplitude.api.Amplitude;

@Kroll.module(name="TitaniumAmplitude", id="ti.amplitude")
public class TitaniumAmplitudeModule extends KrollModule
{
	// Methods

	@Kroll.method
	public void initialize(String apiKey)
	{
		Amplitude.getInstance().initialize(TiApplication.getInstance().getRootOrCurrentActivity(), apiKey);
	}

	@Kroll.method
	public void logEvent(String eventName, KrollDict params)
	{
		if (params != null) {
			try {
				JSONObject jsonObject = new JSONObject(params.toString());
				Amplitude.getInstance().logEvent(eventName, jsonObject);
			} catch (JSONException err){
				Log.d("Error", err.toString());
			}
		} else {
			Amplitude.getInstance().logEvent(eventName);
		}
	}
}
